export const textLightGray = "#6C757D";
export const lightGray = "#CED4DA";
export const lightGreen = "#3BFF48";
export const darkGreen = "#198754";
export const darkRed = "#E23636";
export const redIndicator = "#CF2C1F"; //CF2C1F
export const textDarkGray = "#212529";
export const primaryBlue = "#0D6EFD";
export const white = "#FFFFFF";
export const black = "#000000";
export const seperatorColor = "#5C5E64";
export const orangeDark = "#FF6103";
export const yellowDark = "#F9D200";
export const darkYellow = "#F7A200"; //F7A200
export const yellowMark = "#F9B600";
export const lightCream = "#FDFDD2";
export const mediumCream = "#FFF5BD";
export const darkCream = "#F5F5DC";
export const cream = "#FDFBD4";
export const green = "#56763C";
export const caramel = "#EED797";
export const tumbleWeed = "#D7A389";
export const alaBaster = "#EAECE3";

